language: node_js

git:
  depth: 5

os:
- linux
#- osx

node_js:
- '8'
- '10'
- '12'

before_install:
# update npm to latest?
# - npm install -g npm@5.7.1

# show product version
- nvm --version
- node --version
- npm --version

install:
- npm install
